DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users (
    user_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(200) NOT NULL,
    login       VARCHAR(200) NOT NULL,
    name        VARCHAR(200),
    birthday    DATE,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(20000) NOT NULL,
    releaseDate DATE,
    duration    INT CHECK (duration > 0),
    mpa_id      INT REFERENCES mpa (mpa_id),
    rating      INTEGER
);

CREATE TABLE IF NOT EXISTS friendsList (
    user_id     INTEGER REFERENCES users (user_id),
    friend_id   INTEGER REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS likesList (
    film_id     INTEGER REFERENCES films (film_id),
    user_id     INTEGER REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    film_id     INTEGER REFERENCES films (film_id),
    genre_id    INTEGER REFERENCES genres (genre_id)
);
